POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFrdSIsImlkIjoiNjNmZTAwYTAyNTUxYjM2MWQzMjNiYTZlIiwiaWF0IjoxNjc3NzY2MjAxLCJleHAiOjE2Nzc3Njk4MDF9.4ZFOD2eZtVfLg6GVQswPrwGs6irMOV2CtJaNrabBNdE

{
  "title": "Akun blogi",
  "author": "313 auto",
  "url": "https://akuankka.com",
  "likes": 313
}