POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer xxxxx

{
  "title": "Tupun blogi",
  "author": "1 ankka",
  "url": "https://tupuankka.com",
  "likes": 1
}